"""Deterministic manifest, C++ include, and report emission."""

import json
from pathlib import Path

import mpmath as mp

from . import __version__


def _decimal(value, digits=50):
	return mp.nstr(value, digits, strip_zeros=False)


def emit(output: Path, spec, chebyshev_error, remez, quantization, verification):
	output.mkdir(parents=True, exist_ok=True)
	resolved_spec = json.loads(json.dumps(spec.raw))
	resolved_spec["public_interval"] = [_decimal(value) for value in spec.public_interval]
	resolved_spec["reduced_interval"] = [_decimal(value) for value in spec.interval]
	manifest = {
		"tool": {"name": "fixmath-approx", "version": __version__, "required_dependency": f"mpmath {mp.__version__}"},
		"specification": resolved_spec,
		"chebyshev": {"estimated_maximum_error": _decimal(chebyshev_error)},
		"remez": {
			"converged": remez.converged, "iterations": remez.iterations, "error_amplitude": _decimal(remez.error_amplitude),
			"coefficients_ascending": [_decimal(value) for value in remez.coefficients],
			"reference_points": [_decimal(value) for value in remez.reference_points],
			"extrema": [{"x": _decimal(x), "error": _decimal(error)} for x, error in remez.extrema],
		},
		"quantization": {
			"method": "deterministic coordinate neighborhood search", "radius": spec.quantize_radius, "evaluations": quantization.evaluations, "sampled_raw_inputs_per_evaluation": quantization.sampled_inputs,
			"coefficient_polynomial": "q(z), z = x^2",
			"full_polynomial_powers_ascending": [2 * power + 1 for power in spec.powers],
			"initial_raw_coefficients_ascending": quantization.initial_raw_coefficients,
			"raw_coefficients_ascending": quantization.raw_coefficients,
			"raw_coefficients_horner_order": list(reversed(quantization.raw_coefficients)),
			"fixed_coefficient_extrema": [{"x": _decimal(x), "error": _decimal(error)} for x, error in quantization.extrema],
		},
		"verification": {
			"level": verification.level, "checked_raw_inputs": verification.checked_inputs,
			"maximum_implemented_error_ulp": verification.maximum_implemented_error_ulp, "worst_raw_input": verification.worst_raw_input,
			"maximum_real_error": _decimal(verification.maximum_real_error), "worst_real_input": _decimal(verification.worst_real_input),
			"maximum_numerator_bits": verification.maximum_numerator_bits, "maximum_stage_raw": verification.maximum_stage_raw, "overflow_observed": verification.overflow,
		},
	}
	(output / "manifest.json").write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
	constants = ",\n\t".join(str(value) for value in reversed(quantization.raw_coefficients))
	full_powers_descending = ", ".join(f"x^{2 * power + 1}" for power in reversed(spec.powers))
	raw_type = f"int{spec.width}_t"
	inl = f"""// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Generated by fixmath-approx {__version__}; do not edit.
// {spec.name}: Q{spec.width - spec.fraction_bits}:{spec.fraction_bits}, x * q(x^2), x in [0, pi/4].
// The constants are q coefficients in descending Horner order; the full polynomial
// has powers {full_powers_descending} and no constant term.
// Verification: {verification.level}, maximum observed error {verification.maximum_implemented_error_ulp} ulp.
inline constexpr {raw_type} {spec.name.upper()}_COEFFICIENTS[] = {{
	{constants},
}};
"""
	(output / "coefficients.inl").write_text(inl, encoding="utf-8-sig", newline="\n")
	report = f"""# {spec.name} approximation report

- Basis: `x * q(x^2)`, degree {2 * (len(spec.powers) - 1) + 1} in x
- Full-polynomial powers: `{[2 * power + 1 for power in spec.powers]}` ascending; there is no constant term and `p(0) = 0` exactly
- Format and evaluator: Q{spec.width - spec.fraction_bits}:{spec.fraction_bits}, {spec.rounding}, stage-by-stage Horner rounding
- Remez: {'converged' if remez.converged else 'not converged'} in {remez.iterations} iterations
- Raw coefficients (descending Horner order): `{list(reversed(quantization.raw_coefficients))}`
- Verification level: `{verification.level}` ({verification.checked_inputs} distinct raw inputs)
- Maximum implemented error: {verification.maximum_implemented_error_ulp} ulp at raw input {verification.worst_raw_input}
- Maximum sampled real error: {_decimal(verification.maximum_real_error)}
- Largest signed numerator width: {verification.maximum_numerator_bits} bits; overflow observed: {verification.overflow}

`sampled` is numerical evidence, not a proof over all raw inputs in the declared Q format.
"""
	(output / "report.md").write_text(report, encoding="utf-8", newline="\n")
	return manifest
